# Generated by Django 5.1.1 on 2024-09-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=500)),
                ('middleName', models.CharField(max_length=500)),
                ('lastName', models.CharField(max_length=500)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('cellPhoneNumber', models.CharField(max_length=12)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
